# Generated by Django 5.0.3 on 2024-03-05 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0006_remove_cost_id_alter_cost_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cost', serialize=False, to='trip_app.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='trip_app.customer'),
        ),
    ]
