# Generated by Django 5.0.3 on 2024-03-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0010_alter_location_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
